/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsTripIdIndexRouteImport } from './routes/trips.$tripId.index'
import { Route as TripsTripIdBookingsRouteImport } from './routes/trips.$tripId.bookings'
import { Route as TripsTripIdInsightsRouteImport } from './routes/trips.$tripId.insights'
import { Route as TripsTripIdMapRouteImport } from './routes/trips.$tripId.map'
import { Route as TripsTripIdPlacesRouteImport } from './routes/trips.$tripId.places'
import { Route as TripsTripIdPlanRouteImport } from './routes/trips.$tripId.plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdIndexRoute = TripsTripIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdBookingsRoute = TripsTripIdBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdInsightsRoute = TripsTripIdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdMapRoute = TripsTripIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdPlacesRoute = TripsTripIdPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdPlanRoute = TripsTripIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => TripsTripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/places': typeof PlacesRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/bookings': typeof TripsTripIdBookingsRoute
  '/trips/$tripId/insights': typeof TripsTripIdInsightsRoute
  '/trips/$tripId/map': typeof TripsTripIdMapRoute
  '/trips/$tripId/places': typeof TripsTripIdPlacesRoute
  '/trips/$tripId/plan': typeof TripsTripIdPlanRoute
  '/trips/$tripId/': typeof TripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/places': typeof PlacesRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/bookings': typeof TripsTripIdBookingsRoute
  '/trips/$tripId/insights': typeof TripsTripIdInsightsRoute
  '/trips/$tripId/map': typeof TripsTripIdMapRoute
  '/trips/$tripId/places': typeof TripsTripIdPlacesRoute
  '/trips/$tripId/plan': typeof TripsTripIdPlanRoute
  '/trips/$tripId': typeof TripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/places': typeof PlacesRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/bookings': typeof TripsTripIdBookingsRoute
  '/trips/$tripId/insights': typeof TripsTripIdInsightsRoute
  '/trips/$tripId/map': typeof TripsTripIdMapRoute
  '/trips/$tripId/places': typeof TripsTripIdPlacesRoute
  '/trips/$tripId/plan': typeof TripsTripIdPlanRoute
  '/trips/$tripId/': typeof TripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/places'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/bookings'
    | '/trips/$tripId/insights'
    | '/trips/$tripId/map'
    | '/trips/$tripId/places'
    | '/trips/$tripId/plan'
    | '/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/places'
    | '/trips/new'
    | '/trips/$tripId/bookings'
    | '/trips/$tripId/insights'
    | '/trips/$tripId/map'
    | '/trips/$tripId/places'
    | '/trips/$tripId/plan'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/places'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/bookings'
    | '/trips/$tripId/insights'
    | '/trips/$tripId/map'
    | '/trips/$tripId/places'
    | '/trips/$tripId/plan'
    | '/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlacesRoute: typeof PlacesRoute
  TripsTripIdRoute: typeof TripsTripIdRouteWithChildren
  TripsNewRoute: typeof TripsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/': {
      id: '/trips/$tripId/'
      path: '/'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof TripsTripIdIndexRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/bookings': {
      id: '/trips/$tripId/bookings'
      path: '/bookings'
      fullPath: '/trips/$tripId/bookings'
      preLoaderRoute: typeof TripsTripIdBookingsRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/insights': {
      id: '/trips/$tripId/insights'
      path: '/insights'
      fullPath: '/trips/$tripId/insights'
      preLoaderRoute: typeof TripsTripIdInsightsRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/map': {
      id: '/trips/$tripId/map'
      path: '/map'
      fullPath: '/trips/$tripId/map'
      preLoaderRoute: typeof TripsTripIdMapRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/places': {
      id: '/trips/$tripId/places'
      path: '/places'
      fullPath: '/trips/$tripId/places'
      preLoaderRoute: typeof TripsTripIdPlacesRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/plan': {
      id: '/trips/$tripId/plan'
      path: '/plan'
      fullPath: '/trips/$tripId/plan'
      preLoaderRoute: typeof TripsTripIdPlanRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
  }
}

interface TripsTripIdRouteChildren {
  TripsTripIdBookingsRoute: typeof TripsTripIdBookingsRoute
  TripsTripIdInsightsRoute: typeof TripsTripIdInsightsRoute
  TripsTripIdMapRoute: typeof TripsTripIdMapRoute
  TripsTripIdPlacesRoute: typeof TripsTripIdPlacesRoute
  TripsTripIdPlanRoute: typeof TripsTripIdPlanRoute
  TripsTripIdIndexRoute: typeof TripsTripIdIndexRoute
}

const TripsTripIdRouteChildren: TripsTripIdRouteChildren = {
  TripsTripIdBookingsRoute: TripsTripIdBookingsRoute,
  TripsTripIdInsightsRoute: TripsTripIdInsightsRoute,
  TripsTripIdMapRoute: TripsTripIdMapRoute,
  TripsTripIdPlacesRoute: TripsTripIdPlacesRoute,
  TripsTripIdPlanRoute: TripsTripIdPlanRoute,
  TripsTripIdIndexRoute: TripsTripIdIndexRoute,
}

const TripsTripIdRouteWithChildren = TripsTripIdRoute._addFileChildren(
  TripsTripIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlacesRoute: PlacesRoute,
  TripsTripIdRoute: TripsTripIdRouteWithChildren,
  TripsNewRoute: TripsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
